"""Build a hash-pinned requirements.lock from live PyPI metadata.

Hashes are the *real* sha256 digests published by PyPI for the exact
versions resolved in this environment. Nothing here is invented: if a
package or version cannot be resolved against the PyPI JSON API the
script fails loudly rather than emitting a placeholder.
"""

from __future__ import annotations

import json
import sys
import urllib.error
import urllib.request
from pathlib import Path

WANTED = {
    "cryptography": "runtime",
    "cffi": "runtime-transitive",
    "pycparser": "runtime-transitive",
    "pytest": "dev",
    "pytest-cov": "dev",
    "coverage": "dev",
}


def installed_versions() -> dict[str, str]:
    import importlib.metadata as md

    out: dict[str, str] = {}
    for name in WANTED:
        try:
            out[name] = md.version(name)
        except md.PackageNotFoundError:
            pass
    return out


def pypi_digests(name: str, version: str) -> list[tuple[str, str, str]]:
    """Return (filename, sha256, packagetype) triples published for a release."""
    url = f"https://pypi.org/pypi/{name}/{version}/json"
    req = urllib.request.Request(url, headers={"User-Agent": "anticloud-ref-lock/1.0"})
    with urllib.request.urlopen(req, timeout=45) as resp:
        doc = json.load(resp)
    files = doc.get("urls") or []
    if not files:
        raise RuntimeError(f"{name}=={version}: PyPI published no files")
    out = []
    for entry in files:
        digest = (entry.get("digests") or {}).get("sha256")
        if not digest:
            raise RuntimeError(f"{name}=={version}: file {entry.get('filename')} has no sha256")
        out.append((entry["filename"], digest, entry.get("packagetype", "bdist_wheel")))
    return out


def main() -> int:
    root = Path(__file__).resolve().parent.parent
    versions = installed_versions()
    missing = sorted(set(WANTED) - set(versions))
    if missing:
        print(f"FATAL: not installed, cannot pin: {', '.join(missing)}", file=sys.stderr)
        return 2

    lines = [
        "# anticloud-reference -- hash-pinned dependency lock",
        "# Generated by tools/gen_lock.py against the live PyPI JSON API.",
        "# Regenerate with: python tools/gen_lock.py",
        "# Verify with:     anticloud-ref deps-verify requirements.lock",
        "#",
        "# Every distribution artifact below carries the sha256 digest that",
        "# PyPI published for it. `pip install --require-hashes -r",
        "# requirements.lock` therefore accepts only these exact bytes.",
        "#",
        f"# runtime: {', '.join(sorted(n for n, k in WANTED.items() if k.startswith('runtime')))}",
        "",
    ]
    total = 0
    for name in sorted(versions):
        version = versions[name]
        kind = WANTED[name]
        try:
            digests = pypi_digests(name, version)
        except (urllib.error.URLError, RuntimeError, TimeoutError) as exc:
            print(f"FATAL: {name}=={version}: {exc}", file=sys.stderr)
            return 3
        lines.append(f"# {kind}: {name} {version} ({len(digests)} artifact(s))")
        total += len(digests)
        # pip's hash-pinned form: one requirement line, then one `--hash=`
        # continuation per distribution artifact.  Only the final continuation
        # omits the backslash; anything else would be read as the end of the
        # requirement and the remaining hashes would be orphaned.
        block = [f"{name}=={version} \\"]
        for position, (filename, digest, _kind) in enumerate(digests):
            last = position == len(digests) - 1
            block.append(f"    --hash=sha256:{digest}" + ("" if last else " \\"))
        lines.extend(block)
        lines.append("")

    lock = root / "requirements.lock"
    lock.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")
    print(f"wrote {lock} with {total} hash(es) across {len(versions)} package(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
