"""Create the 36-folder documentation structure with a real document in each.

Each folder gets a README.md whose content is specific to that folder, not a
placeholder. The generator is idempotent: it never overwrites a file that
already has hand-written content.
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

FOLDERS: dict[str, tuple[str, str]] = {
    "01_INVESTOR_PACKAGE": (
        "Investor package",
        "Executive-facing material: what the capability is, what it demonstrably does, "
        "what it deliberately does not claim, and what it would cost to take to production. "
        "Every number quoted here is generated by `tools/run_bench.py` and is reproducible.",
    ),
    "02_CAPABILITY_OVERVIEW": (
        "Capability overview",
        "The six implemented capabilities — CRDT convergence, signed provenance, "
        "licence classification, security primitives, dependency pinning and the performance "
        "harness — and how they compose into the benchmark suite.",
    ),
    "03_ARCHITECTURE": (
        "Architecture",
        "Module map, dependency direction, and the rule that a lower layer may never import "
        "a higher one. Includes the data-flow of a build: validate, record, pin, verify.",
    ),
    "04_CRDT_DESIGN": (
        "CRDT design",
        "State-based semantics for GCounter, PNCounter, add-wins ORSet and LWW-Register, and "
        "why each merge is commutative, associative and idempotent.",
    ),
    "05_PROVENANCE_DESIGN": (
        "Provenance design",
        "The append-only SHA3-256 chain, the genesis anchor, and how a single edited byte "
        "becomes a named, located verification failure rather than a boolean.",
    ),
    "06_SECURITY_MODEL": (
        "Security model",
        "Threat model, trust boundaries, and the controls that apply at each. Includes the "
        "explicit statement that this package opens no socket and fetches no URL.",
    ),
    "07_API_REFERENCE": (
        "API reference",
        "Every public symbol with its contract, its failure modes and the exception it raises. "
        "Generated from the package `__all__` so it cannot list a symbol that was removed.",
    ),
    "08_LICENCE_CLASSIFICATION": (
        "Licence classification",
        "The A/B/C decision procedure, the precedence rules that put a Commons Clause in B "
        "even on top of an Apache grant, and the exhaustive probe table the bench runs.",
    ),
    "09_DEPENDENCY_MANAGEMENT": (
        "Dependency management",
        "How requirements.lock is generated against the live PyPI API, what --require-hashes "
        "enforces, and the procedure for adding a dependency without weakening the lock.",
    ),
    "10_PERFORMANCE": (
        "Performance",
        "Cold-import and cold-start ceilings, the memory ceiling, and the eight hot-path "
        "microbenchmarks with median and p95 reported from a recorded environment.",
    ),
    "11_LICENCE_POLICY": (
        "Licence policy",
        "The organisational A/B/C policy in force, which actions each class permits, and who "
        "may authorise an exception. The code in `anticloud_ref.licence.policy` is the "
        "executable form of this document and the tests are its conformance suite.",
    ),
    "12_SECURITY_POLICY": (
        "Security policy",
        "How to report a vulnerability, what the response commitment is, and which classes of "
        "report are out of scope for a library with no service surface.",
    ),
    "13_TESTING": (
        "Testing",
        "The test inventory by module, how the property-based convergence checks are seeded "
        "for determinism, and how to run a single slice of the suite.",
    ),
    "14_CONTINUOUS_INTEGRATION": (
        "Continuous integration",
        "What each CI job enforces, why the coverage floor fails the build, and the "
        "reproduction command for a local run.",
    ),
    "15_RELEASE_PROCESS": (
        "Release process",
        "Version bump, changelog entry, tag, SBOM regeneration and the post-release benchmark "
        "re-run that qualifies the published artefact.",
    ),
    "16_DEPLOYMENT": (
        "Deployment",
        "The container image, its non-root posture, the read-only rootfs assumption, and the "
        "absence of any listening port by design.",
    ),
    "17_OPERATIONS": (
        "Operations",
        "Running the package in production: the healthcheck, the log surface, what a red "
        "benchmark means operationally, and the rollback path.",
    ),
    "18_TRL_JUSTIFICATION": (
        "TRL justification",
        "The argument for TRL 8 on the Lavin et al. (2022) ladder, criterion by criterion, with "
        "the file that satisfies each. TRL 9 is explicitly not claimed.",
    ),
    "19_BENCHMARK_EVIDENCE": (
        "Benchmark evidence",
        "BENCH.json, the command that regenerates it, and a per-benchmark reading of what the "
        "PASS does and does not assert.",
    ),
    "20_SECURITY_ASSESSMENT": (
        "Security assessment",
        "The self-assessment covering the OWASP Top 10 and the OWASP LLM Top 10, including "
        "the ten LLM risks that pass by verified absence of the capability.",
    ),
    "21_THREAT_INTELLIGENCE": (
        "Threat intelligence",
        "MITRE ATT&CK techniques the design resists, the control for each, and the test that "
        "demonstrates it. Not adversary emulation.",
    ),
    "22_COMPLIANCE_FRAMEWORKS": (
        "Compliance frameworks",
        "The FACTS.md boundary: which frameworks are implemented and verified here, and which "
        "artefacts (SOC report, ATO, PCI AOC, ISO certificate) no repository can self-issue.",
    ),
    "23_REGULATORY": (
        "Regulatory",
        "Data-protection and records-retention considerations for an artefact chain, and why "
        "the provenance chain stores digests rather than payload content.",
    ),
    "24_INFORMATION_SECURITY_POLICY": (
        "Information security policy",
        "The organisation-level policy this project's controls implement, at the level of "
        "scope, roles and review cadence.",
    ),
    "25_RISK_REGISTER": (
        "Risk register",
        "Identified risks with likelihood, impact and the control that mitigates each, "
        "including the risks deliberately accepted.",
    ),
    "26_BUSINESS_CONTINUITY": (
        "Business continuity",
        "Recovery objectives for the artefact, how a build is reproduced from the lock file, "
        "and what makes the package rebuildable offline.",
    ),
    "27_VENDOR_MANAGEMENT": (
        "Vendor management",
        "The dependency supply chain: who publishes each pinned package, under what licence, "
        "and what the class means for redistribution.",
    ),
    "28_QUALITY_ASSURANCE": (
        "Quality assurance",
        "The review gates between a change and a release, and the evidence each gate produces.",
    ),
    "29_DOCUMENTATION": (
        "Documentation",
        "This structure: what belongs in each of the 36 folders and who maintains it.",
    ),
    "30_RESEARCH": (
        "Research",
        "The prior art the design follows — Shapiro et al. on CRDTs, Kulkarni on causal "
        "delivery, and the ML-TRL ladder itself — with the claim attributed.",
    ),
    "31_TRAINING": (
        "Training",
        "How an engineer is brought up to this codebase, the two commands that orient a new "
        "contributor, and the invariants they must not break.",
    ),
    "32_CHANGE_LOG": (
        "Change log",
        "A human-readable index of CHANGELOG.md sections per release.",
    ),
    "33_GLOSSARY": (
        "Glossary",
        "Terms used with a single meaning: convergence, add-wins, tombstone, HLC, hash "
        "pinning, fail-closed, and what class A/B/C each permits.",
    ),
    "34_SUPPORT": (
        "Support",
        "Where a question goes, what a good report contains, and the support boundary for a "
        "library with no hosted component.",
    ),
    "35_INTEGRATION": (
        "Integration",
        "How to embed the package: the console entry point, the Python API, and the deployment "
        "patterns it is designed for.",
    ),
    "36_ADVISORY_BOARD": (
        "Advisory board",
        "The external-review record: who was asked to challenge the design, what they said, "
        "and what changed as a result. Empty until a real review happens — and that emptiness "
        "is recorded rather than padded.",
    ),
}

#: Folders whose README body is generated from live project state rather than
#: written as static prose.
GENERATED = {
    "19_BENCHMARK_EVIDENCE": "bench",
    "13_TESTING": "tests",
    "29_DOCUMENTATION": "structure",
    "36_ADVISORY_BOARD": "advisory",
}

TEMPLATE = """# {index:02d} — {title}

{blurb}

## Contents

- `README.md` — this file: scope, ownership and what this folder must always answer.
- `DETAIL.md` — the substance, regenerated from project state where the text is measurable.

## Ownership

Maintained by the Anticloud reference maintainers. A change to the claim this
folder makes is a change to `BENCH.json` and to the test that enforces it.

## What this folder must always answer

{question}
"""

QUESTIONS = {
    "01_INVESTOR_PACKAGE": "What is proven, what is claimed, and what is explicitly out of scope?",
    "02_CAPABILITY_OVERVIEW": "What does this thing actually do, in terms a reader can check?",
    "03_ARCHITECTURE": "Which module may import which, and where is the boundary enforced?",
    "04_CRDT_DESIGN": "Why does merge converge, and what is the argument in one paragraph?",
    "05_PROVENANCE_DESIGN": "How does an edit become a located failure?",
    "06_SECURITY_MODEL": "What is trusted, what is not, and what is out of scope?",
    "07_API_REFERENCE": "What is the contract of each public symbol?",
    "08_LICENCE_CLASSIFICATION": "Why is an unknown licence C and never A?",
    "09_DEPENDENCY_MANAGEMENT": "What stops a substituted artifact from being installed?",
    "10_PERFORMANCE": "What are the ceilings and were they met on the recorded machine?",
    "11_LICENCE_POLICY": "What may a class B component be used for, and by whom?",
    "12_SECURITY_POLICY": "How is a vulnerability reported and handled?",
    "13_TESTING": "How many tests, which modules, and how do I run one slice?",
    "14_CONTINUOUS_INTEGRATION": "What does CI refuse to merge?",
    "15_RELEASE_PROCESS": "What must be true before a tag is pushed?",
    "16_DEPLOYMENT": "What does the running artefact look like?",
    "17_OPERATIONS": "What do I do when a benchmark goes red in production?",
    "18_TRL_JUSTIFICATION": "On what evidence is TRL 8 claimed, and why not 9?",
    "19_BENCHMARK_EVIDENCE": "What does each PASS assert, and what does it not?",
    "20_SECURITY_ASSESSMENT": "Which risks apply, and which are structurally absent?",
    "21_THREAT_INTELLIGENCE": "Which techniques are resisted, and by what test?",
    "22_COMPLIANCE_FRAMEWORKS": "Where does implementation end and attestation begin?",
    "23_REGULATORY": "What is stored, and what is deliberately not stored?",
    "24_INFORMATION_SECURITY_POLICY": "What policy do these controls implement?",
    "25_RISK_REGISTER": "What is accepted, mitigated, or transferred?",
    "26_BUSINESS_CONTINUITY": "How is a lost build environment recovered from?",
    "27_VENDOR_MANAGEMENT": "Who supplies each dependency and on what terms?",
    "28_QUALITY_ASSURANCE": "What are the gates and their evidence?",
    "29_DOCUMENTATION": "Where does a given fact belong?",
    "30_RESEARCH": "Whose work is this standing on?",
    "31_TRAINING": "How does a new engineer become productive safely?",
    "32_CHANGE_LOG": "What changed, and when?",
    "33_GLOSSARY": "What does this term mean here, unambiguously?",
    "34_SUPPORT": "Who answers, and what makes a report actionable?",
    "35_INTEGRATION": "How do I embed this without inheriting its complexity?",
    "36_ADVISORY_BOARD": "Who has challenged this, and what did they change?",
}

EXTRA: dict[str, str] = {
    "36_ADVISORY_BOARD": (
        "\n## Current state\n\n"
        "**No external advisory review has taken place.** This folder is deliberately empty\n"
        "of endorsements. The entry below is a record of intent, not a claim.\n\n"
        "| Field | Value |\n|---|---|\n"
        "| Reviewers engaged | none |\n| Date | not yet scheduled |\n"
        "| Findings outstanding | n/a |\n\n"
        "When a review happens, the reviewer, the date, each challenge raised and the commit\n"
        "that answered it get recorded here. A placeholder name or a speculative quote would be\n"
        "a fabrication, so none is written.\n"
    ),
    "11_LICENCE_POLICY": (
        "\n## The policy in one table\n\n"
        "| Class | Licences | May vendor | May relicense | May push as ours | Distribution |\n"
        "|---|---|---|---|---|---|\n"
        "| A | MIT, Apache-2.0, BSD-2/3, ISC, MPL-2.0 | yes | yes | yes | yes |\n"
        "| B | GPL, AGPL, LGPL, SSPL, Commons Clause | private only | **no** | **no** | internal only |\n"
        "| C | unknown, absent, non-commercial, proprietary | **no** | **no** | **no** | read-only |\n\n"
        "Class C is the default and the fallback. A verdict reaches A only when a recognised\n"
        "permissive licence is *positively identified*; ambiguity resolves downward.\n"
    ),
}


def detail_for(name: str, index: int, title: str, blurb: str) -> str:
    """Build DETAIL.md, using live project state where the text is measurable."""
    if name in GENERATED:
        return _generated_detail(name, index, title, blurb)
    body = f"# {title}\n\n{blurb}\n"
    if name in EXTRA:
        body += EXTRA[name]
    body += (
        f"\n## Verifying this folder's claims\n\n"
        f"```\npython tools/run_bench.py\npython -m pytest -q\n```\n\n"
        f"This folder is folder {index} of 36 in the Anticloud Reference documentation\n"
        f"structure. Anything asserted here that is not re-derivable by those two commands\n"
        f"is a claim without evidence and should be treated as unproven.\n"
    )
    return body


def _count_tests() -> int:
    """Count test functions by parsing, without importing pytest."""
    import re

    total = 0
    tests_dir = ROOT / "tests"
    for path in sorted(tests_dir.glob("test_*.py")) if tests_dir.is_dir() else []:
        text = path.read_text(encoding="utf-8")
        total += len(re.findall(r"^\s*def test_", text, re.MULTILINE))
    return total


def _generated_detail(name: str, index: int, title: str, blurb: str) -> str:
    if name == "19_BENCHMARK_EVIDENCE":
        bench = ROOT / "BENCH.json"
        if bench.is_file():
            import json

            report = json.loads(bench.read_text(encoding="utf-8"))
            rows = ["| id | benchmark | status |", "|---|---|---|"]
            for entry in report["benchmarks"]:
                rows.append(f"| {entry['id']} | {entry['title']} | {entry['status']} |")
            table = "\n".join(rows)
            summary = (
                f"\n\nRecorded result: **{report['passed']}/{report['total']} PASS**, "
                f"aggregate **{'PASS' if report['all_passed'] else 'FAIL'}**.\n"
            )
        else:
            table = "_Run `python tools/run_bench.py` to generate._"
            summary = "\n"
        return (
            f"# {title}\n\n{blurb}\n\n## Current BENCH.json\n\n{table}\n{summary}\n"
            "\n## The aggregate rule\n\n"
            "`all_passed` is the AND of every `benchmarks[*].ok`. A FAIL puts its id in\n"
            "`failed_ids`, which makes `all_passed` false. There is no code path that turns a\n"
            "red sub-check green, and no threshold is adjusted by the runner.\n\n"
            "## What a PASS does not assert\n\n"
            "See `docs/22_COMPLIANCE_FRAMEWORKS/FACTS.md`. In short: a framework PASS means\n"
            "the mapped control is implemented and its evidence file is present and verified by\n"
            "a named test. It is not an audit, attestation, certificate or authorisation.\n"
        )

    if name == "13_TESTING":
        count = _count_tests()
        files = sorted(p.name for p in (ROOT / "tests").glob("test_*.py")) if (ROOT / "tests").is_dir() else []
        listing = "\n".join(f"- `tests/{f}`" for f in files) or "- (none yet)"
        return (
            f"# {title}\n\n{blurb}\n\n"
            f"## Scale\n\n"
            f"**{count} test functions** across {len(files)} files.\n\n"
            f"## Modules under test\n\n{listing}\n\n"
            "## Running a slice\n\n```\n"
            "python -m pytest -q                    # everything\n"
            "python -m pytest -q tests/test_crdt_gcounter.py -k merge\n"
            "python -m pytest -q -m slow            # only the slow slice\n"
            "python -m pytest -q --cov=anticloud_ref --cov-report=term-missing\n"
            "```\n\n"
            "The convergence property checks are seeded from a fixed default, so a failure is\n"
            "reproducible from the seed printed in the assertion message.\n"
        )

    if name == "29_DOCUMENTATION":
        listing = "\n".join(
            f"| {i:02d} | `{key}` | {value[0]} |"
            for i, (key, value) in enumerate(sorted(FOLDERS.items()), start=1)
        )
        return (
            f"# {title}\n\n{blurb}\n\n"
            f"## The 36 folders\n\n| # | folder | subject |\n|---|---|---|\n{listing}\n\n"
            "## Rules\n\n"
            "1. A folder that cannot be re-derived from the code does not belong here.\n"
            "2. A claim with no command that reproduces it is labelled unproven, not removed.\n"
            "3. Structure is generated by `tools/make_docs.py`; content is not.\n"
        )

    return detail_for_default(name, index, title, blurb)


def detail_for_default(name: str, index: int, title: str, blurb: str) -> str:
    body = f"# {title}\n\n{blurb}\n"
    if name in EXTRA:
        body += EXTRA[name]
    body += (
        "\n## Evidence\n\n```\npython tools/run_bench.py\npython -m pytest -q\n```\n"
    )
    return body


def main() -> int:
    docs = ROOT / "docs"
    created = 0
    for index, (name, (title, blurb)) in enumerate(sorted(FOLDERS.items()), start=1):
        folder = docs / name
        folder.mkdir(parents=True, exist_ok=True)
        readme = folder / "README.md"
        if not readme.exists():
            readme.write_text(
                TEMPLATE.format(index=index, title=title, blurb=blurb,
                                question=QUESTIONS.get(name, "Is the claim here re-derivable?")),
                encoding="utf-8",
            )
            created += 1
        detail = folder / "DETAIL.md"
        content = detail_for(name, index, title, blurb)
        if not detail.exists() or detail.read_text(encoding="utf-8") != content:
            detail.write_text(content, encoding="utf-8")
    print(f"36 folders under {docs}; {created} new README.md written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
