"""Security: input validation, secret scanning, safe writes, an encrypted vault."""

from anticloud_ref.security.safeio import (
    PRIVATE_MODE,
    PathTraversalError,
    SafeWriteError,
    resolve_within,
    safe_write_bytes,
    safe_write_json,
    safe_write_text,
    write_lines,
)
from anticloud_ref.security.secrets import (
    Finding,
    redact,
    scan_text,
    scan_tree,
    shannon_entropy,
)
from anticloud_ref.security.validators import (
    ValidationError,
    validate_bool,
    validate_choices,
    validate_element,
    validate_hex_digest,
    validate_int,
    validate_iterable,
    validate_node_id,
    validate_nonneg_int,
    validate_path,
    validate_port,
    validate_text,
)
from anticloud_ref.security.vault import (
    DecryptionError,
    SealedBlob,
    SecretVault,
    VaultError,
    decrypt,
    derive_key,
    encrypt,
)

__all__ = [
    "PRIVATE_MODE",
    "DecryptionError",
    "Finding",
    "PathTraversalError",
    "SafeWriteError",
    "SealedBlob",
    "SecretVault",
    "ValidationError",
    "VaultError",
    "decrypt",
    "derive_key",
    "encrypt",
    "redact",
    "resolve_within",
    "safe_write_bytes",
    "safe_write_json",
    "safe_write_text",
    "scan_text",
    "scan_tree",
    "shannon_entropy",
    "validate_bool",
    "validate_choices",
    "validate_element",
    "validate_hex_digest",
    "validate_int",
    "validate_iterable",
    "validate_node_id",
    "validate_nonneg_int",
    "validate_path",
    "validate_port",
    "validate_text",
    "write_lines",
]
